/* Shared time, family money and preparation. All amounts are in 10,000 JPY. */
(function(root){
'use strict';
const D=root.LifeData,X=root.LifeSystems,A=root.LifeAdmissions;
const copy=v=>JSON.parse(JSON.stringify(v)),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
const log=(s,title,text,kind='life')=>{s.history.unshift({age:s.age,title,text,kind});s.history=s.history.slice(0,800);};
D.EDITION='4.1';D.SUBJECTS.mathIII='数学Ⅲ';D.SUBJECTS.higherMath='大学数学（線形代数・解析）';
for(const c of Object.values(D.CURRICULA))c.weights=[...c.weights,0,0];
D.CURRICULA.sciences.weights=[1,1,2,2,1,1,1,0,0,0,0,1,2,0];
D.CURRICULA.medicine.weights=[1,1,2,2,1,0,2,1,0,0,0,0,2,0];
D.CURRICULA.custom.weights=[2,2,1,2,1,1,1,0,1,0,0,1,0,0];
D.MATH_TRACKS=[['age','学年に合わせる'],['arithmetic','算数の計算・図形'],['juniorMath','中学数学'],['mathI','数学Ⅰ・A'],['mathII','数学Ⅱ・B・C'],['mathIII','数学Ⅲ（微積分）'],['higherMath','大学数学（線形代数・解析）']];
D.PARENT_PLANS=[['talk','食事のときに学校の話をする'],['read','親と一緒に本を読む'],['chores','皿洗い・洗濯物たたみを手伝う'],['discuss','門限・進路・買い物の条件を話し合う'],['distance','言い争う前に、別室で落ち着く'],['hide','成績や使ったお金を隠す']];
const names={books:'学研の図鑑LIVE「昆虫」',blocks:'LEGO Classic 10698',instrument:'YAMAHA P-145 電子ピアノ',bike:'ブリヂストン エブリッジ L',laptop:'Lenovo IdeaPad Slim 3',desk:'IKEA MICKE デスク＋学習チェア',workstation:'Apple Mac mini M4 Pro',camera:'Canon EOS R50',sportsgear:'ASICS GEL-CONTEND ランニングセット',bed:'西川 Air 01 マットレス',console:'Nintendo Switch 2',librarypass:'市立図書館の利用カード',gym:'chocoZAP 月額会員',tutor:'明光義塾・週1回の個別指導',professional:'TAC・公認会計士講座',cleaner:'ベアーズ・月1回の家事代行',pet:'保護猫「むぎ」を迎える',car:'スズキ アルト L',luxurycar:'レクサス ES300h',trip:'京都・奈良 2泊3日の鉄道旅行',abroad:'台北・語学学校の4週間コース',checkup:'内科健診＋歯科クリーニング',donation:'市民科学・図書購入基金への寄付'};
for(const i of D.ITEMS){i.name=names[i.id]||i.name;i.parentEligible=['books','blocks','instrument','bike','laptop','desk','sportsgear','bed','tutor','professional'].includes(i.id);if(i.id==='instrument')i.minAge=5;}
Object.assign(D.ITEMS.find(i=>i.id==='console'),{price:5,upkeep:0,minAge:6});
D.ITEMS.push(
 {id:'mariokart',name:'マリオカート ワールド',kind:'hobby',price:.9,minAge:6,requiresItem:'console',happy:1.4,stress:-.4,life:12,icon:'gamepad',desc:'Switch 2本体が必要。家族や友人と対戦するソフト。'},
 {id:'dictionary',name:'CASIO EX-word XD-SX4920',kind:'learning',price:4.2,minAge:10,parentEligible:true,study:.04,life:8,icon:'book',desc:'辞書を引いて復習。学習効率+4%。購入だけでは語学力は増えない。'},
 {id:'guitar',name:'YAMAHA FG800 アコースティックギター',kind:'creative',price:3.5,minAge:8,parentEligible:true,creative:.05,upkeep:.3,life:18,icon:'music',desc:'楽器練習に使用。弦の交換費は年3,000円。'},
 {id:'mathbook',name:'チャート式 基礎からの数学Ⅲ＋C',kind:'learning',price:.25,minAge:6,parentEligible:true,life:12,icon:'book',desc:'先取り学習の教材。数学Ⅱの理解が足りないと学習は進みにくい。'},
 {id:'allowancebook',name:'コクヨ キャンパス おこづかい帳',kind:'learning',price:.03,minAge:6,life:3,icon:'wallet',desc:'支出を記録する。年末の家計理解+1。'},
 {id:'snack',name:'明治 ミルクチョコレート 10枚',kind:'experience',price:.02,minAge:6,happy:.6,repeat:true,icon:'gift',desc:'今年1セット。小遣いから買って友人と分ける。'}
);
Object.assign(D.ITEMS.find(i=>i.id==='books'),{name:'福音館書店『いないいないばあ』',price:.09,maxAge:5,desc:'親と一緒にページをめくる。読み聞かせの時間の学習効率+5%。'});
D.ITEMS.find(i=>i.id==='sportsgear').minAge=6;D.ITEMS.find(i=>i.id==='donation').minAge=18;D.ITEMS.find(i=>i.id==='trip').minAge=6;
D.ITEMS.push({id:'insectbook',name:'学研の図鑑LIVE『昆虫 新版』',kind:'learning',price:.27,minAge:6,parentEligible:true,study:.03,life:10,icon:'book',desc:'公園で見つけた虫を調べる。自習の学習効率+3%。'});
const driver=D.EXAMS.find(e=>e.id==='driver');driver.note='教習所で学科・技能・仮免・路上教習を修了し、本免許へ。「免許・移動」で準備します。';
const old={init:X.init,migrate:X.migrate,plan:X.plan,normalize:X.normalize,train:X.train,extraBudget:X.extraBudget,yearEnd:X.yearEnd,afterTrain:X.afterTrain,validate:X.validate,jobGate:X.jobGate,jobScore:X.jobScore,action:X.action};
function plan(age,previous={}){return {...old.plan(age,previous),mathTrack:previous.mathTrack||'age',parentPlan:previous.parentPlan||'talk',purchaseFunding:previous.purchaseFunding||'pocket',nightFrequency:previous.nightFrequency||0,travelFrequency:previous.travelFrequency||0,drinkDays:age<20?0:previous.drinkDays??0,cigarettes:age<20?0:previous.cigarettes??0,partyFrequency:age<20?0:previous.partyFrequency??0,competitionFrequency:previous.competitionFrequency||0,codePractice:previous.codePractice||0,musicPractice:previous.musicPractice||0,drivingPractice:previous.drivingPractice||0,sciencePair:previous.sciencePair||'physics,chemistry',socialSubject:previous.socialSubject||'history',socialSecond:previous.socialSecond||'geography',commonTrack:previous.commonTrack||'science',humanitiesMath:!!previous.humanitiesMath,essayPractice:previous.essayPractice||0,reservePrivate:previous.reservePrivate??true,attendance:previous.attendance||'regular',transport:previous.transport||'public',applications:[],quizSubject:previous.quizSubject||'math',ai:age<16?'off':previous.ai||'off'};}
function upgradeAdmissions(s){
 if(s.admissionVersion===1)return s;
 s.plan.essayPractice??=0;s.plan.reservePrivate??=true;s.admissions.essaySkill??=Math.min(200,s.skills.language*.55);
 s.admissions.migrationNotes=[];
 for(const ap of s.plan.applications||[]){const u=root.UNIVERSITIES.find(u=>u.id===ap.university),c=u?.courses[ap.course];if(!c)continue;const r=A.route(u,c,ap.route);if(r.id!==ap.route){s.admissions.migrationNotes.push(u.name+' '+c.faculty+'：学科と方式の対応を修正しました。出願の詳細を確認してください。');ap.route=r.id;}ap.selection=root.LifeAdmissionRules.resolve(s,u,c,r,ap.selection).selection;}
 for(const p of s.presets||[])p.essayPractice??=0;
 s.admissionVersion=1;return s;
}
function init(s,opts={}){
 if(s.nextVersion===4)return upgradeAdmissions(s);
 const legacy=!!opts.legacy;delete s.admissionVersion;s.nextVersion=4;s.pacing=opts.pacing==='term'?'term':'year';s.period=0;s.termPlans=[];s.termReports=[];s.presets=[];s.autoYears=0;s.yearExperiencePaid=null;
 Object.assign(s.plan,plan(s.age,s.plan));s.plan.subjectWeights=[...(s.plan.subjectWeights||D.CURRICULA.balanced.weights)];while(s.plan.subjectWeights.length<14)s.plan.subjectWeights.push(0);
 s.subjects.mathIII=legacy&&s.age>=17?Math.min(s.subjects.mathII||0,s.skills.math*.6):0;s.subjects.higherMath=legacy&&s.degrees.some(d=>d.field==='science')?Math.min(100,s.skills.math*.4):0;
 s.learning={arithmetic:legacy?clamp((s.subjects.mathI||0)*1.5,0,200):0,juniorMath:legacy?clamp(s.subjects.mathI||0,0,200):0};
 s.parents={bond:s.family.warmth,trust:65,autonomy:s.age>=18?100:15,educationFund:legacy?0:{supported:40,standard:12,independent:3}[s.background],aiConsent:false,lastTopup:s.age,decisions:0};
 s.admissions={mocks:[],results:[],common:null};s.driving={stage:s.certs.driver!==undefined?'licensed':'none',theory:0,practice:0,tests:0,issued:s.certs.driver??null};
 s.competition={rating:0,algorithm:0,entries:0,best:0,tourPoints:0,invited:false,worlds:0};s.music={skill:0,recitals:0,awards:0};s.quiz={year:s.age,attempted:false,correct:false,question:null};s.yearStats={income:0,spending:0,startingWealth:0};s.school.repeats??=0;s.workCulture=((s.rng>>>0)%3===0)?'party':'mixed';
 if(!legacy)s.cash=0;
 if(legacy){const tokyo=root.UNIVERSITIES.find(u=>u.name==='東京大学');for(const ap of [s.goal,s.plan.admission])if(ap?.university===tokyo.id){const c=A.legacyTokyo[ap.course],field=c?.field;ap.course=field==='medicine'?5:field==='tech'?3:['science','pharmacy','veterinary'].includes(field)?4:field==='law'?0:field==='business'?1:2;}}
 if(s.plan.admission?.kind==='college'){const ap=s.plan.admission,u=root.UNIVERSITIES.find(u=>u.id===ap.university);s.plan.applications=[{...ap,route:A.routes(u,u.courses[ap.course])[0].id}];s.plan.admission=null;}
 return upgradeAdmissions(s);
}
function allowance(s){if(s.age<6)return 0;const monthly=s.age<12?.06+s.age*.007:s.age<15?.3:.5;return Math.round(monthly*12*({supported:1.5,standard:1,independent:.6}[s.background])*100)/100;}
function parentBudget(s){return {supported:50,standard:18,independent:5}[s.background];}
function payEducation(s,cost){if(!Number.isFinite(cost)||cost<0)return false;const parental=s.age<18?Math.min(cost,s.parents.educationFund):0;if(s.cash<cost-parental)return false;s.parents.educationFund-=parental;s.cash-=cost-parental;return true;}
function mathTrack(s){return s.plan.mathTrack==='age'?(s.age<12?'arithmetic':s.age<15?'juniorMath':s.age===15?'mathI':s.age===16?'mathII':['sciences','medicine'].includes(s.plan.curriculum)?'mathIII':'mathII'):s.plan.mathTrack;}
function train(s,add,eff,amount){
 const before=copy(s.subjects);old.train(s,add,eff,amount);s.subjects=before;
 if(s.age>=12&&s.plan.essayPractice)s.admissions.essaySkill=clamp(s.admissions.essaySkill+s.plan.essayPractice*10*eff*(1-s.admissions.essaySkill/270),0,200);
 const a=s.plan.allocation,weights=s.plan.subjectWeights,track=mathTrack(s),prior={juniorMath:'arithmetic',mathI:'juniorMath',mathII:'mathI',mathIII:'mathII',higherMath:'mathIII'},value=k=>s.learning[k]??s.subjects[k]??0;
 const parent=s.age<12?.78+s.parents.bond/250:1,auto=1,night=Math.min(52,s.plan.nightFrequency),recovery=1-Math.min(.3,night*.006),gainScale=parent*auto*recovery;
 const mathWeight=weights[1]+weights[2]+weights[12]+weights[13];let mGain=(amount*2.4*mathWeight/12+(s.age>=15?12:s.age>=6?7:1))*gainScale;
 if(prior[track]&&value(prior[track])<35)mGain*=.15+value(prior[track])/50;
 const apply=(k,g)=>{const target=k in s.learning?s.learning:s.subjects;target[k]=clamp((target[k]||0)+g*(1-(target[k]||0)/270),0,200);};
 apply(track,mGain);
 // Upper secondary mathematics is distinct. Studying I/A never supplies III or university mathematics.
 if(s.age>=15&&s.highschool!=='none'&&!s.highschoolGrad){if(track!=='mathI')apply('mathI',6);if(s.school.hsProgress>=1&&track!=='mathII')apply('mathII',5);}
 Object.keys(D.SUBJECTS).forEach((k,i)=>{if(['mathI','mathII','mathIII','higherMath'].includes(k))return;const advanced=['physics','chemistry','biology'].includes(k);const attending=s.age<15||s.highschool!=='none'&&!s.highschoolGrad||s.education&&!s.education.paused;const regular=s.age>=6&&attending?(advanced?(s.age>=15?12:s.age>=12?5:0):6):0;const early=s.age<6?.15:s.age<12&&advanced?.25:1;apply(k,(amount*2.5*weights[i]/12+regular)*early*gainScale);});
}
function academicYear(s){const base=s.learning,sub=s.subjects;if(s.age===12)base.juniorMath=Math.max(base.juniorMath,base.arithmetic*.65);if(s.age===15)sub.mathI=Math.max(sub.mathI,base.juniorMath*.75);if(s.age===16)sub.mathII=Math.max(sub.mathII,sub.mathI*.70);if(s.age===17&&['sciences','medicine'].includes(s.plan.curriculum))sub.mathIII=Math.max(sub.mathIII,sub.mathII*.45);}
function commitments(s){const p=s.plan;return {study:p.essayPractice+(p.exams.length*.5)+(p.applications.length*.25)+(p.drivingPractice?2:0)+(p.experience&&D.EXPERIENCES.find(x=>x.id===p.experience)&&!['mentor','local','club','counsel'].includes(p.experience)?D.EXPERIENCES.find(x=>x.id===p.experience).needTime:0),creative:p.codePractice+p.musicPractice+(p.experience==='club'?1:0)+(p.project!=='none'?1:0),social:s.age<12&&p.parentPlan!=='distance'?1:0,rest:Math.ceil(p.travelFrequency/3)+(s.purchasesThisYear.some(v=>['trip','abroad'].includes(v))?1:0)};}
function planError(s){const p=s.plan;if(s.age<12&&p.essayPractice)return'小論文対策は12歳からです';if(s.period>0&&(p.experience!==s.termPlans[0].experience||p.project!==s.termPlans[0].project))return'年間テーマ・長期プロジェクトは年度の途中で変更できません';if(p.transport==='car'&&(!s.items.some(i=>['car','luxurycar'].includes(i.id))||s.certs.driver===undefined))return'車での移動には普通免許と車が必要です';if(s.age<20&&(p.drinkDays||p.cigarettes||p.partyFrequency))return'酒・タバコの設定は20歳からです';if(s.age<12&&p.nightFrequency)return'徹夜の設定は中学生以降です';if(s.age<6&&p.travelFrequency)return'渡航回数の指定は6歳からです';if(s.age<16&&p.ai!=='off')return'この年齢では生成AIを使う学習は選べません';if(s.age<18&&p.ai!=='off'&&!s.parents.aiConsent)return'AIの使用は、先に親と利用条件を相談してください';if(p.ai!=='off'&&s.inner.digital<20)return'生成AIの利用には手続き力20以上が必要です';
 const dt=s.pacing==='term'?1/3:1,options=(optionCosts(s)-(s.age>=18&&s.job&&s.region==='local'&&p.transport==='public'?18:0))*dt+(splitCount(p.travelFrequency,s)-p.travelFrequency*dt)*22;if(root.LifeEngine&&options>s.cash+Math.max(0,periodBudget(s,root.LifeEngine.annualBudget(s)).net+options))return'旅行・嗜好品・習い事の予算が不足しています。回数を減らすか、現金を貯めてください';
 const req=commitments(s);for(const [k,v]of Object.entries(req))if(v>p.allocation[k])return`${D.ACTIVITIES.find(a=>a.id===k).name}が不足しています。予定${v}コマ／配分${p.allocation[k]}コマ`;
 if(p.socialSubject===p.socialSecond)return'社会の第1・第2科目は別の科目を選んでください';if(p.applications.length&&(p.admission||p.school))return'大学出願とほかの進学予定は同時に設定できません';if(p.codePractice&&s.age<6)return'競技プログラミングは6歳からです';if(p.musicPractice&&!s.items.some(i=>['instrument','guitar'].includes(i.id)))return'楽器を購入してから練習を設定してください';if(p.drivingPractice&&s.driving.stage==='none')return'先に教習所へ申し込んでください';if(p.drivingPractice&&s.driving.stage==='licensed')return'免許取得済みです。教習の時間を外してください';
 if(p.competitionFrequency&&(!p.codePractice||!s.items.some(i=>['laptop','workstation','librarypass'].includes(i.id))))return'大会には練習時間とPCまたは図書館利用カードが必要です';return'';
}
function optionCosts(s){const p=s.plan;return p.travelFrequency*22+(s.age>=20?p.drinkDays*.035+p.cigarettes*365*.003+p.partyFrequency*.45:0)+p.codePractice*.3+p.musicPractice*.6+(s.age>=18&&s.job&&s.region==='local'&&p.transport==='public'?18:0);}
function recurringBudget(s){const fee=old.extraBudget(s),p=s.plan;let legacy=0;if(s.age>=20)for(const k of ['alcohol','tobacco'])legacy+=D.LIFESTYLE[k].find(x=>x[0]===p[k])?.[2]||0;if(s.job&&p.networking==='party')legacy+=8;return fee-legacy+optionCosts(s);}
function splitCount(n,s){return s.pacing==='term'?Math.floor(n*(s.period+1)/3)-Math.floor(n*s.period/3):n;}
function trainingFraction(s,fn,dt){if(dt===1){fn(s);return;}const before={skills:copy(s.skills),subjects:copy(s.subjects),inner:copy(s.inner),learning:copy(s.learning),discipline:s.stats.discipline,essay:s.admissions.essaySkill};fn(s);for(const k of ['skills','subjects','inner','learning'])for(const id of Object.keys(before[k]))s[k][id]=before[k][id]+(s[k][id]-before[k][id])*dt;s.stats.discipline=before.discipline+(s.stats.discipline-before.discipline)*dt;s.admissions.essaySkill=before.essay+(s.admissions.essaySkill-before.essay)*dt;}
function perPeriod(s,report,rand,dt){const p=s.plan;
 if(s.age<18){const f=s.parents,id=p.parentPlan;const d={talk:[3,1,1],read:[2,1,0],chores:[1,3,2],discuss:[2,2,4],distance:[0,0,1],hide:[-3,-6,0]}[id];f.bond+=d[0]*dt;f.trust+=d[1]*dt;f.autonomy+=d[2]*dt;f.decisions++;s.stats.stress+=((s.family.pressure-45)*.025-(id==='distance'?2:0))*dt;if(id==='read'){s.skills.language+=dt*1.4;s.subjects.japanese+=dt;}if(id==='chores'&&s.age>=6)s.cash+=.12*dt;if(id==='hide')s.stats.stress+=dt*2;if(s.age<6){s.stats.happiness+=(f.bond-50)*.018*dt;s.inner.resilience+=dt*(f.bond/100);}
  if(id==='discuss'&&s.age>=16&&f.trust>=40)f.aiConsent=true;
  report.push({kind:'life',text:s.age<6?({talk:'泣いたときに声をかけ、抱っこして落ち着くのを待った。',read:'寝る前に絵本を一冊。好きなページでは手を伸ばすようになった。',chores:'おもちゃの片づけを一緒に練習。箱に入れられたら声をかけた。',discuss:'保護者同士で寝かしつけと家事を分担し、生活リズムをそろえた。',distance:'明かりと音を控えめにして、昼寝と休息の時間を増やした。',hide:'家の中の会話が減り、親との距離が広がった。'}[id]):`${D.PARENT_PLANS.find(x=>x[0]===id)[1]}。親との信頼 ${Math.round(f.trust)}。`});
 }
 const nights=p.nightFrequency*dt;if(nights){s.stats.health-=nights*.22;s.stats.stress+=nights*.32;s.inner.fatigue+=nights*.5;s.inner.academicConfidence+=Math.min(1,nights*.15);report.push({kind:'life',text:`テスト前の徹夜：この期間は約${nights.toFixed(1)}回。提出物は進んだが、翌日の集中力が落ちた。`});}
 if(s.age>=20){s.stats.health-=(p.drinkDays*.012+p.cigarettes*.13)*dt;s.body.alcoholDependence+=(p.drinkDays*.035-2)*dt;s.body.tobaccoDependence+=(p.cigarettes*.4-3)*dt;s.body.burden+=(p.drinkDays*.003+p.cigarettes*.045)*dt;const parties=p.partyFrequency*dt;if(s.job&&parties){const culture=s.workCulture==='party',gain=Math.min(6,parties*.6)*(culture&&p.drinkDays===0?.65:1);s.stats.connections+=gain;s.inner.fatigue+=parties*.12;report.push({kind:'life',text:`同僚との食事会に${parties.toFixed(1)}回相当参加。${p.drinkDays?'飲酒する日と飲まない日を決めて参加した。':culture?'飲酒中心の職場。二次会の輪には入りづらいが、一次会で話せた。':'ノンアルコールで会話に加わった。'}`});}}
 const trips=splitCount(p.travelFrequency,s);if(trips){s.visits+=trips;s.skills.english+=Math.min(5,trips*1.8);s.subjects.englishL+=Math.min(5,trips*1.5);s.inner.selfKnowledge+=Math.min(3,trips);report.push({kind:'life',text:`海外へ${trips}往復。${s.age<18?'保護者と一緒に移動し、現地であいさつや買い物を体験した。':'乗り継ぎ・宿泊・現地での買い物を自分で手配した。'}`});
  for(let i=0;i<trips*2;i++){const r=rand(s);if(r<.12/1e6&&s.lifeMode==='natural'){s.finished=true;s.endCause='航空事故';log(s,'搭乗便で重大事故','航空事故により人生が終了した。非常に低い頻度のゲーム内再現。','end');report.push({kind:'fail',text:'搭乗便で重大事故が発生し、人生が終了しました。'});break;}else if(r<1.27/1e6){s.stats.health-=12;s.stats.stress+=15;report.push({kind:'fail',text:'搭乗便で事故が発生。救助後、医療機関で検査を受けた。'});}}
 }
 if(p.drivingPractice&&s.driving.stage!=='licensed'){const d=s.driving;d.theory=Math.min(26,d.theory+26*dt);d.practice=Math.min(31,d.practice+31*dt);d.stage=d.theory>=13&&s.age+(s.period+1)/(s.pacing==='term'?3:1)>=17.5?'provisional':'school';if(d.theory>=26-1e-6&&d.practice>=31-1e-6&&s.age+(s.period+1)/(s.pacing==='term'?3:1)>=18){d.tests++;const score=s.inner.digital*.25+s.stats.discipline*.35+s.skills.tech*.4;if(score>=25){d.stage='licensed';d.issued=Math.floor(s.age+(s.period+1)/(s.pacing==='term'?3:1)+1e-6);s.certs.driver=d.issued;p.drivingPractice=0;report.push({kind:'success',text:'修了検定・仮免・路上教習・卒業検定・本免学科を修了。普通自動車免許（AT）を取得した。'});log(s,'普通自動車免許を取得','教習所の学科26時限・技能31時限を修了した。','exam');}else{d.stage='road';report.push({kind:'fail',text:'本免学科の模擬採点は合格点に届かなかった。次の期間も復習して再受験する。'});}}else report.push({kind:'life',text:`自動車教習：学科${Math.floor(d.theory)}/26・技能${Math.floor(d.practice)}/31時限。`});}
 if(p.codePractice){const c=s.competition;c.algorithm=clamp(c.algorithm+p.codePractice*6*dt*(1-c.algorithm/250),0,200);const entries=splitCount(p.competitionFrequency,s);for(let i=0;i<entries;i++){const perf=clamp(s.skills.tech*9+(s.subjects.mathII||0)*3+c.algorithm*9+(rand(s)-.5)*220-s.stats.stress*2,0,4000);c.entries++;c.best=Math.max(c.best,Math.round(perf));c.rating=Math.round(c.rating*.86+Math.max(0,perf-Math.max(0,10-c.entries)*50)*.14);c.tourPoints+=Math.max(0,perf-2900)/100;}if(entries)report.push({kind:'life',text:`競プロに${entries}回参加。計算量・二分探索・動的計画法を復習。レーティング ${c.rating}。`});if(c.rating>=2800&&c.tourPoints>=35&&!c.invited){c.invited=true;report.push({kind:'success',text:'国際大会「LIFE CODE WORLD FINAL」への招待が届いた。レートと年間ツアーポイントの両条件を満たした。'});log(s,'競プロ国際大会に招待','LIFE CODE WORLD FINALへの参加資格を獲得。架空の大会。','project');}}
 if(p.musicPractice){s.music.skill=clamp(s.music.skill+p.musicPractice*4.2*dt*(1-s.music.skill/260),0,200);s.stats.happiness+=p.musicPractice*.4*dt;}
 if(s.items.some(i=>i.id==='allowancebook'))s.inner.financial+=dt;
 normalize(s);
}
function yearEnd(s,report,rand){
 if(s.age<17){s.parents.educationFund=Math.min(100,s.parents.educationFund+parentBudget(s));s.parents.lastTopup=s.age+1;}
 if(s.music.skill>=35&&s.plan.musicPractice>0){s.music.recitals++;s.impact+=1;if(s.music.skill>=130&&s.plan.musicPractice>=2){s.music.awards++;s.cash+=2;report.push({kind:'success',text:'地域の器楽コンクールで入賞。賞金2万円を受け取り、課題曲を録音した。'});}else report.push({kind:'life',text:'発表会で1曲を演奏。止まった小節を、次の練習ノートに書き出した。'});}
 if(s.competition.invited){s.competition.worlds++;s.competition.invited=false;s.competition.tourPoints=0;s.impact+=10;report.push({kind:'success',text:`競プロ国際大会に出場。世界大会の出場記録は${s.competition.worlds}回になった。`});}
 s.competition.tourPoints*=.45;
}
function itemGate(s,i){if(i.requiresItem&&!s.items.some(v=>v.id===i.requiresItem))return`${D.ITEMS.find(v=>v.id===i.requiresItem).name}が必要です`;if(['trip','abroad'].includes(i.id)&&s.purchasesThisYear.filter(v=>['trip','abroad'].includes(v)).length>=1)return'単発の旅行・留学は今年1つまでです';if(['trip','abroad'].includes(i.id)&&s.plan.allocation.rest<1)return'旅行には休息・余暇を1コマ以上確保してください';return'';}
function parentPays(s,i){return s.age<6||s.age<18&&s.plan.purchaseFunding==='parent'&&i.parentEligible&&s.parents.trust>=35;}
function canAffordItem(s,i){return parentPays(s,i)?s.parents.educationFund>=i.price:s.cash>=i.price;}
function payItem(s,i){const parent=parentPays(s,i);if(parent)s.parents.educationFund-=i.price;else s.cash-=i.price;return parent;}
function action(s,type){
 if(type==='driving-enroll'){if(s.finished)return'この人生は完結しています';if(s.driving.stage!=='none')return'教習または免許の記録があります';if(s.age<17)return'17歳の年度から教習を計画できます';if(!payEducation(s,30))return'教習費30万円が必要です';s.driving.stage='school';log(s,'自動車教習所に入校','普通AT限定コース。時間配分で教習2コマを確保する。');return'';}
 if(type==='ai-permission'){if(s.age<16||s.age>=18)return'16〜17歳で親と相談できます';if(s.parents.trust<40)return'成績や利用時間を共有し、親との信頼を40以上にしてください';s.parents.aiConsent=true;return'';}
 if(type.startsWith('campus:')&&s.age<12)return'小学校の学籍は維持します。通学が難しい場合は「親との相談」や支援の物語を選べます';
 return old.action(s,type);
}
function normalize(s){if(!s.nextVersion)return;for(const k of ['bond','trust','autonomy'])s.parents[k]=clamp(s.parents[k]);s.parents.educationFund=Math.round(clamp(s.parents.educationFund,0,100)*10000)/10000;for(const k of Object.keys(s.learning))s.learning[k]=clamp(s.learning[k],0,200);s.school.repeats=clamp(s.school.repeats,0,100);}
function examLevel(s,e,base){if(!e.id.startsWith('suken'))return base;const index=Number(e.id.replace('suken',''));if(index>=12)return Math.min(base,s.subjects.mathIII||0,s.subjects.higherMath||0);if(index===11)return Math.min(base,s.subjects.mathIII||0);if(index>=9)return Math.min(base,s.subjects.mathI||0,s.subjects.mathII||0);if(index>=6)return Math.min(base,s.learning.juniorMath||0);return Math.min(base,s.learning.arithmetic||0);}
function savePreset(s,name){name=String(name||'').trim().slice(0,24);if(!name)return'プリセット名を入力してください';if(s.presets.length>=12&&!s.presets.some(p=>p.name===name))return'保存は12件までです';const p={name,allocation:copy(s.plan.allocation),subjectWeights:copy(s.plan.subjectWeights),focus:s.plan.focus,curriculum:s.plan.curriculum,mathTrack:s.plan.mathTrack,sciencePair:s.plan.sciencePair,socialSubject:s.plan.socialSubject,socialSecond:s.plan.socialSecond,commonTrack:s.plan.commonTrack,essayPractice:s.plan.essayPractice};const i=s.presets.findIndex(v=>v.name===name);if(i<0)s.presets.push(p);else s.presets[i]=p;return'';}
function loadPreset(s,index){const p=s.presets[index];if(!p)return'プリセットが見つかりません';const {name,...values}=copy(p);Object.assign(s.plan,values);return'';}
function validate(s){const num=(v,a,b)=>Number.isFinite(v)&&v>=a&&v<=b;if(s.nextVersion!==4||!['year','term'].includes(s.pacing)||!Number.isInteger(s.period)||s.period<0||s.period>2)return false;
 if(!s.parents||!['bond','trust','autonomy'].every(k=>num(s.parents[k],0,100))||!num(s.parents.educationFund,0,100)||typeof s.parents.aiConsent!=='boolean')return false;
 if(!s.learning||!num(s.learning.arithmetic,0,200)||!num(s.learning.juniorMath,0,200)||!Array.isArray(s.presets)||s.presets.length>12||!Array.isArray(s.termPlans)||s.termPlans.length>2)return false;
 if(s.presets.some(p=>typeof p.name!=='string'||p.name.length>24||!p.allocation||!Array.isArray(p.subjectWeights)||p.subjectWeights.length!==14||p.subjectWeights.some(n=>!Number.isInteger(n)||n<0||n>12)||!validAllocation(p.allocation)||p.subjectWeights.reduce((a,b)=>a+b,0)>12||!D.CURRICULA[p.curriculum]||!['balanced',...Object.keys(D.SKILLS)].includes(p.focus)||!D.MATH_TRACKS.some(t=>t[0]===p.mathTrack)))return false;
 const p=s.plan;if(s.termPlans.length!==s.period||s.pacing==='year'&&s.period!==0||s.termPlans.some(t=>!validAllocation(t.allocation)||t.experience&&!D.EXPERIENCES.some(x=>x.id===t.experience)||!D.PROJECTS.some(x=>x.id===t.project)||!['regular','often','rare'].includes(t.attendance)))return false;if(!['science','humanities'].includes(p.commonTrack)||![p.socialSubject,p.socialSecond].every(v=>['history','geography','civics'].includes(v))||!['physics,chemistry','chemistry,biology','physics,biology'].includes(p.sciencePair))return false;if(!D.MATH_TRACKS.some(v=>v[0]===p.mathTrack)||!D.PARENT_PLANS.some(v=>v[0]===p.parentPlan)||!['pocket','parent'].includes(p.purchaseFunding)||!['regular','often','rare'].includes(p.attendance)||!['public','car'].includes(p.transport))return false;
 for(const[k,max]of Object.entries({nightFrequency:52,travelFrequency:12,drinkDays:365,cigarettes:40,partyFrequency:48,competitionFrequency:24,codePractice:3,musicPractice:3,drivingPractice:1,essayPractice:2}))if(!Number.isInteger(p[k])||!num(p[k],0,max))return false;
 if(!Array.isArray(p.applications)||p.applications.length>7||p.applications.some(ap=>{const u=root.UNIVERSITIES.find(u=>u.id===ap.university);return !u||!Number.isInteger(ap.course)||!u.courses[ap.course]||!['full','night'].includes(ap.mode)||!routesValid(u,u.courses[ap.course],ap.route)||!ap.selection||!A.selectionValid(s,u,u.courses[ap.course],A.route(u,u.courses[ap.course],ap.route),ap.selection);} ))return false;
 if(s.admissionVersion!==1||typeof p.reservePrivate!=='boolean'||!validApplications(s)||s.presets.some(v=>!Number.isInteger(v.essayPractice)||!num(v.essayPractice,0,2)))return false;
 if(!s.admissions||!num(s.admissions.essaySkill,0,200)||!Array.isArray(s.admissions.results)||!Array.isArray(s.admissions.mocks)||s.admissions.mocks.length>60||!s.driving||!['none','school','provisional','road','licensed'].includes(s.driving.stage))return false;
 if(!['theory','practice','tests'].every(k=>num(s.driving[k],0,k==='theory'?26:k==='practice'?31:300))||!s.termReports||!Array.isArray(s.termReports)||s.termReports.length!==s.period)return false;
 if(!s.competition||!num(s.competition.rating,0,4000)||!num(s.competition.algorithm,0,200)||!s.music||!num(s.music.skill,0,200)||!s.quiz||typeof s.quiz.attempted!=='boolean')return false;if(!['entries','worlds','best','tourPoints'].every(k=>num(s.competition[k],0,100000))||!['recitals','awards'].every(k=>num(s.music[k],0,300)))return false;if(s.quiz.question&&(!Array.isArray(s.quiz.question.choices)||s.quiz.question.choices.length!==4||typeof s.quiz.question.prompt!=='string'||!Number.isInteger(s.quiz.question.correct)||s.quiz.question.correct<0||s.quiz.question.correct>3||![...Object.keys(D.SUBJECTS),'arithmetic','juniorMath'].includes(s.quiz.question.key)))return false;return true;
}
function validApplications(s){const seen=new Set(),rounds=new Set();let privateCount=0,foreignCount=0;for(const ap of s.plan.applications){const key=ap.university+'|'+ap.course+'|'+ap.route;if(seen.has(key))return false;seen.add(key);const u=root.UNIVERSITIES.find(u=>u.id===ap.university),r=A.route(u,u.courses[ap.course],ap.route),round=A.publicRound(u,r);if(round&&rounds.has(round))return false;if(round)rounds.add(round);if(u.type==='私立')privateCount++;if(u.foreign)foreignCount++;}return privateCount<=3&&foreignCount<=2;}
function validAllocation(a){return !!a&&D.ACTIVITIES.every(v=>Number.isInteger(a[v.id])&&a[v.id]>=0&&a[v.id]<=12)&&Object.keys(a).length===D.ACTIVITIES.length&&Object.values(a).reduce((x,y)=>x+y,0)<=12;}
function routesValid(u,c,id){return A.routes(u,c).some(r=>r.id===id);}
function schoolFee(s){if(s.age>=6&&s.age<15)return D.CAMPUS[s.school.attendance].fee+(s.age>=12?D.SCHOOL_ROUTES.find(r=>r.id===s.school.middle)?.annual||0:0);if(s.age>=15&&!s.highschoolGrad&&s.highschool!=='none'&&!s.education)return D.SCHOOL_ROUTES.find(r=>r.id===s.school.secondary)?.annual||0;return 0;}
function familyBudget(s,b,dt=1){const funded=s.items.filter(o=>o.parentFunded).reduce((n,o)=>n+(D.ITEMS.find(i=>i.id===o.id)?.upkeep||0),0);const exp=D.EXPERIENCES.find(x=>x.id===s.plan.experience),experienceCost=b.experienceCost??(exp&&!X.experienceEligible(s,exp.id)?exp.cost:0);const education=(b.tuition||0)+schoolFee(s)*dt+funded*dt+experienceCost;const contribution=s.age<18?Math.min(s.parents.educationFund,education):0;return {...b,experienceCost,parentContribution:contribution,expenses:b.expenses-contribution,net:b.net+contribution};}
function periodBudget(s,b){const dt=s.pacing==='term'?1/3:1,first=s.period===0;const parental=b.parentContribution||0;const base={...b,expenses:b.expenses+parental,net:b.net-parental,parentContribution:0};for(const k of Object.keys(base))if(typeof base[k]==='number')base[k]*=dt;const x=D.EXPERIENCES.find(x=>x.id===s.plan.experience);const cost=x&&!X.experienceEligible(s,x.id)?x.cost:0;const adjustment=cost*((first?1:0)-dt)+(splitCount(s.plan.travelFrequency,s)-s.plan.travelFrequency*dt)*22;base.experienceCost=cost*(first?1:0);base.extra+=adjustment;base.expenses+=adjustment;base.net-=adjustment;return familyBudget(s,base,dt);}
function coverDeficit(s,report){if(s.cash>=0)return;const deficit=-s.cash,draw=Math.min(s.investments,deficit);s.investments-=draw;s.cash=0;const debt=deficit-draw;if(debt>0){s.debt+=debt;s.stats.stress+=4;report.push({kind:'fail',text:`不足分${debt.toFixed(1)}万円を生活債務に計上。次の期間の支出を見直そう。`});}}
function termEvent(s){const baby=s.age<6,child=s.age<12,school=s.age<18;const p=s.period;const title=baby?(p===0?'寝る前の絵本を選ぶ':'公園で、初めての遊具'):child?(p===0?'夏休みの自由研究':'友だちと放課後の約束'):school?(p===0?'最初の定期テストが返ってきた':'部活と課題の締切が重なった'):(p===0?'休みの日に予定が3つ':'今月の明細を開いた');const labels=baby?['一緒に指さして名前を読む','外で体を動かす','疲れる前に昼寝をする']:child?['親に相談して材料を集める','友だちと一緒に取り組む','ひとりで図書館を調べる']:school?['間違えた問題をノートに整理する','先生や先輩に質問する','今日は早く寝て明日に備える']:['必要な支出と予定を先に決める','友人と食事をして話す','予定を一つ減らして休む'];const effects=baby?[{language:.8},{health:1},{stress:-2}]:[{discipline:1},{connections:1},{stress:-2}];return{id:'period_'+p,title,text:baby?'親がそばで見守っている。今日は何を一緒にしよう。':child?'使える時間と小遣いは限られている。まず一つ決めよう。':school?'やることを全部詰めると、睡眠が削れる。今回の優先順位を決める。':'予定表と残高を見ながら、今期の使い方を決める。',choices:labels.map((label,i)=>({label,detail:'この4か月のできごと',effects:effects[i]})),periodEvent:true};}
function periodTitle(s){return s.pacing==='term'?['4〜7月','8〜11月','12〜3月'][s.period]:'4月〜翌3月';}
function passingAttendance(s){const plans=s.termPlans.length?s.termPlans:[{attendance:s.plan.attendance}];const score=plans.reduce((n,p)=>n+({regular:1,often:.65,rare:0}[p.attendance||'regular']),0)/plans.length;return score>=(s.plan.allocation.study>=3?.6:.75);}
function averagedAllocation(s){const all=s.termPlans.map(p=>p.allocation);return Object.fromEntries(D.ACTIVITIES.map(a=>[a.id,all.reduce((n,p)=>n+p[a.id],0)/all.length]));}
function finishYear(s){s.yearExperiencePaid=null;s.period=0;s.termPlans=[];s.termReports=[];s.yearStats={income:0,spending:0,startingWealth:0};s.quiz={year:s.age,attempted:false,correct:false,question:null,recent:s.quiz.recent||[]};}
function autoAdvance(s,years){const E=root.LifeEngine;if(!Number.isInteger(years)||years<1||years>10)return{error:'1〜10年を指定してください'};if(s.period!==0)return{error:'年度の途中です。3月まで進めてから自動進行してください'};const start=s.age,notes=[];let stop='指定年数まで進めました';s.autoActive=true;
 try{while(!s.finished&&s.age<start+years){if(s.age>start&&[11,14,17,18,22,65].includes(s.age)){stop='受験・進路・働き方を選ぶ年に着いたため停止';break;}if(s.age>=18&&E.annualBudget(s).net<0&&s.cash<Math.abs(E.annualBudget(s).net)){stop='次年度の資金が不足するため停止';break;}if(s.body.condition||s.stats.health<35){stop='体調の確認が必要なため停止';break;}s.plan.event=0;const r=E.advance(s);if(r.error){stop=r.error;break;}if(s.period===0)notes.push(`${s.age}歳：${r.report.entries.filter(e=>e.kind==='success'||e.kind==='fail').slice(0,2).map(e=>e.text).join(' / ')||'同じ計画を継続'}`);s.report=null;}}finally{s.autoActive=false;}s.autoYears+=s.age-start;return{years:s.age-start,stop,notes};}
X.init=(s,o,r)=>init(old.init(s,o,r),o);X.migrate=s=>{const v=old.migrate(s);return v&&v.expansion===2?init(v,{legacy:true}):v;};X.plan=plan;X.train=train;X.extraBudget=recurringBudget;X.action=action;
X.normalize=s=>{old.normalize(s);normalize(s);};X.validate=s=>old.validate(s)&&validate(s);
X.jobGate=(s,j)=>{const oldReason=old.jobGate(s,j);if(oldReason)return oldReason;if(s.region==='local'&&['farmer','estate','sales'].includes(j.id)&&(!s.items.some(i=>['car','luxurycar'].includes(i.id))||s.certs.driver===undefined))return'この地域の求人は車で訪問する仕事です。普通免許と車が必要';return'';};
X.jobScore=(s,j)=>old.jobScore(s,j)+(j.sector==='tech'?Math.min(12,s.competition.rating/250):0);
X.yearEnd=(s,report,r,focus)=>{yearEnd(s,report,r);old.yearEnd(s,report,r,focus);};
root.LifeNext={academicYear,init,plan,allowance,parentBudget,payEducation,train,mathTrack,commitments,planError,optionCosts,splitCount,trainingFraction,perPeriod,yearEnd,itemGate,parentPays,canAffordItem,payItem,action,normalize,examLevel,savePreset,loadPreset,validate,familyBudget,periodBudget,coverDeficit,termEvent,periodTitle,passingAttendance,averagedAllocation,finishYear,autoAdvance};
})(typeof window!=='undefined'?window:globalThis);
