const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=fs.existsSync(path.join(__dirname,'index.html'))?__dirname:path.join(__dirname,'..');global.window=global;
for(const n of ['universities','data','world','systems','chapters','admission-data','admission-rules','admissions','quiz','next','engine'])require(path.join(root,n+'.js'));
const D=LifeData,E=LifeEngine,A=LifeAdmissions,R=LifeAdmissionRules,N=LifeNext;let checks=0;
const ok=(v,m)=>{assert.ok(v,m);checks++;},eq=(v,w,m)=>{assert.deepEqual(v,w,m);checks++;},near=(v,w)=>ok(Math.abs(v-w)<1e-7,`${v} != ${w}`);
function at(age=18){const s=E.newGame({seed:'v41-test',origin:'medium',prefecture:'13',lifeMode:'century'});s.age=age;s.cash=1000;s.highschoolGrad=age>=18;s.school.hsProgress=Math.min(3,Math.max(0,age-15));s.plan.allocation={study:5,work:0,health:2,social:2,creative:1,rest:2};s.stats.stress=20;for(const k of Object.keys(s.subjects))s.subjects[k]=125;s.admissions.essaySkill=125;return s;}
const uni=name=>UNIVERSITIES.find(u=>u.name===name),course=(u,f)=>u.courses.find(c=>c.faculty===f);
const keio=uni('慶應義塾大学'),meiji=uni('明治大学'),chuo=uni('中央大学'),rikkyo=uni('立教大学'),tokyo=uni('東京大学');
const plan=(s,u,c,r,option)=>({university:u.id,course:u.courses.indexOf(c),mode:'full',route:r.id,selection:R.resolve(s,u,c,r,{option,context:R.context(s)}).selection});
function invariance(u,c,r,option){const s=at(),selection=R.resolve(s,u,c,r,{option}).selection,base=A.estimate(s,u,c,r.id,false,selection);ok(base.probability>0);for(const k of base.unused){const n=E.copy(s);n.subjects[k]=0;eq(A.estimate(n,u,c,r.id,false,selection).probability,base.probability,`unused ${u.name} ${r.department} ${option} ${k}`);n.subjects[k]=200;eq(A.estimate(n,u,c,r.id,false,selection).probability,base.probability);}return base;}
// Narrow subject routes must be immune to every unused academic subject.
for(const faculty of ['経済学部','商学部','総合政策学部','環境情報学部','法学部','文学部','看護医療学部','医学部','理工学部','薬学部']){const c=course(keio,faculty);for(const r of A.routes(keio,c))for(const v of R.variants(at(),keio,c,r))invariance(keio,c,r,v.id);}
{const c=course(keio,'総合政策学部'),r=A.route(keio,c),s=at();for(const k of Object.keys(s.subjects))s.subjects[k]=0;s.subjects.englishR=150;s.admissions.essaySkill=150;const e=A.estimate(s,keio,c,r.id,false,{option:'english'});ok(e.probability>.9,'English and essay can succeed without mathematics');eq(e.common,null);eq(e.used.sort(),['englishR','essay']);const bad=E.copy(s);bad.admissions.essaySkill=0;ok(A.estimate(bad,keio,c,r.id,false,{option:'english'}).probability<e.probability);}
{const c=course(keio,'環境情報学部'),r=A.route(keio,c),s=at();s.subjects.mathIII=0;eq(A.estimate(s,keio,c,r.id,false,{option:'math'}).probability,0);ok(A.estimate(s,keio,c,r.id,false,{option:'english'}).probability>0);}
{const c=course(meiji,'商学部'),r=A.routes(meiji,c).find(r=>r.department==='商学部別');ok(r,'Faculty route must not be lost when matching 商');const e=invariance(meiji,c,r,'history');eq(e.subjects.status,'official');ok(!e.used.includes('mathI'));const math=R.resolve(at(),meiji,c,r,{option:'math'});near(Object.values(R.weights(math.individual)).reduce((a,b)=>a+b,0),350);}
{const c=course(chuo,'総合政策学部'),r=A.routes(chuo,c).find(r=>r.department.includes('一般2'));const e=invariance(chuo,c,r,'standard');eq(e.used.sort(),['englishR','japanese']);}
{const c=rikkyo.courses.find(c=>c.faculty==='経済学部'&&c.department==='経済学科');ok(A.routes(rikkyo,c).every(r=>!r.department.includes('経済政策')),'Do not conflate Economics and Economic Policy');const r=A.routes(rikkyo,c).find(r=>r.deviation!==null),s=at(),e=invariance(rikkyo,c,r,'history');ok(e.used.includes('englishR')&&e.used.includes('englishL'));s.subjects.englishR=0;s.subjects.englishL=0;ok(A.estimate(s,rikkyo,c,r.id,false,{option:'history'}).probability<e.probability,'Two on-campus subjects never waive English');}
// Common-only uses its subset and never imposes mathematics III or an individual exam.
{const c=course(meiji,'商学部'),r=A.routes(meiji,c).find(r=>r.deviation===null);const e=invariance(meiji,c,r,'standard');eq(e.deviation,null);ok(!e.used.includes('mathIII'));ok(!e.used.includes('higherMath'));eq(e.subjects.individual.length,0);eq(A.applicationCost(meiji,r),1.8);}
{const c=course(meiji,'経営学部'),r=A.routes(meiji,c).find(r=>r.department.includes('共テ併3'));const e=invariance(meiji,c,r,'information');eq(e.subjects.common,['information']);const s=at();s.subjects.information=0;ok(A.estimate(s,meiji,c,r.id,false,{option:'information'}).probability<e.probability);}
{const s=at(),c=tokyo.courses[3],r=A.route(tokyo,c),base=A.estimate(s,tokyo,c,r.id,false);s.subjects.japanese=0;ok(A.estimate(s,tokyo,c,r.id,false).probability<base.probability,'Broad national admission still requires Japanese');}
// All selected science variants assess exactly one science in the three-subject model.
{const u=UNIVERSITIES.find(u=>u.type==='私立'&&u.courses.some(c=>c.field==='tech'&&A.routes(u,c).some(r=>r.deviation!==null&&r.subjectCount==='3')));const c=u.courses.find(c=>c.field==='tech'&&A.routes(u,c).some(r=>r.deviation!==null&&r.subjectCount==='3')),r=A.routes(u,c).find(r=>r.deviation!==null&&r.subjectCount==='3');const e=invariance(u,c,r,'physics');eq(e.used.filter(k=>['physics','chemistry','biology'].includes(k)),['physics']);}
// Snapshots survive later global changes and can be edited without an extra application.
{const s=at(),c=course(meiji,'商学部'),r=A.routes(meiji,c).find(r=>r.department==='商学部別');eq(A.add(s,plan(s,meiji,c,r,'history')),'');const before=E.copy(s.plan.applications[0].selection),p=A.estimate(s,meiji,c,r.id,false).probability;s.plan.socialSubject='civics';s.plan.sciencePair='chemistry,biology';eq(s.plan.applications[0].selection,before);eq(A.estimate(s,meiji,c,r.id,false).probability,p);eq(A.add(s,plan(s,meiji,c,r,'math'),0),'');eq(s.plan.applications.length,1);eq(s.plan.applications[0].selection.option,'math');ok(E.validateState(E.migrate(E.copy(s))));const bad=E.copy(s);bad.plan.applications[0].selection.option='invented';ok(!E.validateState(bad));}
const late=UNIVERSITIES.flatMap(u=>u.type==='国立'?u.courses.flatMap(c=>A.routes(u,c).filter(r=>r.round==='後期').map(r=>({u,c,r}))):[])[0];
function mixed(s){const c=course(keio,'経済学部');eq(A.add(s,plan(s,tokyo,tokyo.courses[0],A.route(tokyo,tokyo.courses[0]))),'');eq(A.add(s,plan(s,keio,c,A.routes(keio,c)[0])),'');eq(A.add(s,plan(s,late.u,late.c,late.r)),'');for(const k of Object.keys(s.subjects))s.subjects[k]=200;s.admissions.essaySkill=200;return s;}
{const s=mixed(at());ok(!!A.add(s,plan(s,tokyo,tokyo.courses[1],A.route(tokyo,tokyo.courses[1]))));const c=course(keio,'経済学部');eq(A.add(s,plan(s,keio,c,A.routes(keio,c)[1])),'');const f=course(keio,'総合政策学部');eq(A.add(s,plan(s,keio,f,A.route(keio,f),'english')),'');ok(!!A.add(s,plan(s,keio,course(keio,'環境情報学部'),A.route(keio,course(keio,'環境情報学部')),'english')));eq(s.plan.applications.length,5);ok(E.validateState(s));}
// Funds conservation, deposit loss, exactly one enrolment, and late-round suppression.
{const s=mixed(at()),cash=s.cash,q=A.quote(s);const report=[];A.settle(s,report,()=>0);eq(s.education.university,tokyo.id);eq(s.admissions.results.filter(r=>r.enrolled).length,1);ok(s.admissions.results.find(r=>r.round==='後期').skipped);eq(s.admissions.expenses.reservation,26);eq(s.admissions.expenses.enrollment,28);near(cash-s.cash,Object.values(s.admissions.expenses).reduce((a,b)=>a+b,0));ok(s.cash>=0);ok(q.hold===26);}
{const s=mixed(at()),draws=[.999,0,.999,.999];A.settle(s,[],()=>draws.shift()??.999);eq(s.education.university,keio.id);eq(s.admissions.expenses.reservation,26);eq(s.admissions.expenses.enrollment,0,'Reserved entry fee is never paid twice');}
{const s=mixed(at()),draws=[.999,0,.999,.999];s.plan.reservePrivate=false;A.settle(s,[],()=>draws.shift()??.999);ok(!s.education);ok(s.admissions.results.find(r=>r.university===keio.id).expired);eq(s.admissions.expenses.reservation,0);}
{const s=mixed(at());s.cash=10;const before=s.cash;A.settle(s,[],()=>0);ok(!s.education);ok(s.cash>=0);near(before-s.cash,s.admissions.expenses.exams);ok(s.admissions.results.some(r=>r.unfunded));}
{const s=at(),c=course(keio,'経済学部');eq(A.add(s,plan(s,keio,c,A.routes(keio,c)[0])),'');eq(A.add(s,plan(s,tokyo,tokyo.courses[0],A.route(tokyo,tokyo.courses[0]))),'');s.cash=3.5;A.settle(s,[],()=>.999);eq(s.admissions.expenses.exams,3.5);ok(s.admissions.results.some(r=>r.name==='東京大学'&&r.unfunded));eq(s.cash,0);}
{const s=mixed(at());A.settle(s,[],()=>.999);ok(!s.education);eq(s.admissions.expenses.reservation,0);eq(s.admissions.expenses.enrollment,0);}
{const s=at(17);s.cash=0;s.parents.educationFund=1.7;s.school.hsProgress=3;s.highschoolGrad=true;eq(A.add(s,plan(s,tokyo,tokyo.courses[0],A.route(tokyo,tokyo.courses[0]))),'');A.settle(s,[],()=>.999);eq(s.cash,0);eq(s.parents.educationFund,0);}
// An unaffordable higher-ranked private offer cannot keep public later rounds open.
{const s=mixed(at());[s.plan.applications[0],s.plan.applications[1]]=[s.plan.applications[1],s.plan.applications[0]];s.prefecture='13';const overseas=uni('マサチューセッツ工科大学');s.plan.applications[0]=plan(s,overseas,overseas.courses[0],A.route(overseas,overseas.courses[0]));s.cash=40;A.settle(s,[],()=>0);eq(s.education.university,tokyo.id);ok(s.admissions.results.find(r=>r.round==='後期').skipped);ok(s.admissions.results.find(r=>r.university===overseas.id).unfunded);}
// Essays use the same finite study time; period projections are proportional.
{const base=at(17),b=E.copy(base);b.plan.essayPractice=2;ok(N.commitments(b).study-N.commitments(base).study===2);const p=E.projected(b),plain=E.projected(base);ok(p.admissions.essaySkill>b.admissions.essaySkill);ok(p.subjects.englishR<plain.subjects.englishR);const t=E.copy(b);t.pacing='term';t.period=2;const end=E.projected(t);near(end.admissions.essaySkill-b.admissions.essaySkill,(p.admissions.essaySkill-b.admissions.essaySkill)/3);eq(N.savePreset(b,'論文対策'),'');b.plan.essayPractice=0;eq(N.loadPreset(b,0),'');eq(b.plan.essayPractice,2);ok(E.validateState(b));b.plan.allocation.study=1;b.plan.allocation.rest=6;ok(!!N.planError(b));}
{const s=at(11);s.plan.essayPractice=1;ok(!!N.planError(s));}
{const s=at(),c=course(keio,'総合政策学部');eq(A.add(s,plan(s,keio,c,A.route(keio,c),'english')),'');const p=A.studyPlan(s);eq(p.weights.reduce((a,b)=>a+b,0),12);eq(p.weights[Object.keys(D.SUBJECTS).indexOf('englishR')],12);ok(p.essay);}
// 4.0-shaped saves are upgraded once; progress, money and RNG are retained.
for(const age of [0,10,17,35]){const s=at(age);delete s.admissionVersion;delete s.admissions.essaySkill;delete s.plan.essayPractice;delete s.plan.reservePrivate;const before={age:s.age,cash:s.cash,rng:s.rng};const out=E.migrate(s);eq({age:out.age,cash:out.cash,rng:out.rng},before);ok(E.validateState(out));eq(E.migrate(E.copy(out)),out);}
{const s=at();delete s.admissionVersion;s.plan.applications=[{university:rikkyo.id,course:rikkyo.courses.findIndex(c=>c.department==='経済学科'),route:'r11546',mode:'full'}];E.migrate(s);ok(s.admissions.migrationNotes.length===1);ok(s.plan.applications[0].route!=='r11546');ok(E.validateState(s));}
// Every catalog course/route can form a finite, bounded profile, including reference rows.
let routes=0;const state=at();for(const u of UNIVERSITIES)for(const c of u.courses)for(const r of A.routes(u,c)){const e=A.estimate(state,u,c,r.id,false);ok(Number.isFinite(e.probability)&&e.probability>=0&&e.probability<1,`${u.name}/${c.faculty}/${r.department}`);ok(e.breakdown.every(v=>Number.isFinite(v.level)&&v.points>0));ok(!e.subjects.commonOnly||e.subjects.individual.length===0);routes++;}
const result={passed:true,checks,routeProfiles:routes,features:['required-subject invariance','official narrow routes','per-application snapshots','public-private combination','fees and reservation','essay time sharing','4.0 migration']};fs.writeFileSync(path.join(root,'v41-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
