const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=fs.existsSync(path.join(__dirname,'index.html'))?__dirname:path.join(__dirname,'..');
const qa=fs.existsSync(path.join(root,'tools'))?path.join(root,'qa'):root;
global.window=global;for(const n of ['universities','data','world','systems','chapters','admission-data','admission-rules','admissions','quiz','next','engine'])require(path.join(root,n+'.js'));
const D=LifeData,E=LifeEngine,N=LifeNext,A=LifeAdmissions,Q=LifeQuiz;let checks=0,periods=0;const ok=(v,m)=>{assert.ok(v,m);checks++;},eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++;},near=(a,b,t=.05)=>ok(Math.abs(a-b)<t,`${a} != ${b}`);
function at(age=18,pacing='year',seed='v4'){const s=E.newGame({origin:'medium',lifeMode:'century',seed,pacing});s.age=age;s.cash=3000;s.highschoolGrad=age>=18;s.school.hsProgress=age>=18?3:Math.max(0,age-15);s.stats.discipline=75;s.inner.digital=70;s.plan.allocation={study:4,work:1,health:2,social:2,creative:1,rest:2};return s;}
function tick(s){s.plan.event=0;const r=E.advance(s);ok(!r.error,r.error);ok(E.validateState(s),`invalid age ${s.age}, period ${s.period}`);eq(E.migrate(E.copy(s)),s,'V4 migration must not change a valid save');periods++;return r;}
function nextYear(s){const year=s.age;do{tick(s);}while(s.age===year&&!s.finished);}
// The public-data table preserves all numeric facts with source/page provenance.
eq(new Set(ADMISSION_DATA.rows.map(r=>r[8])).size,14);ok(A.coverage.rows>22000);ok(A.coverage.universities>750);
for(const r of ADMISSION_DATA.rows){ok(UNIVERSITIES.some(u=>u.id===r[0]));ok(r[4]===null||r[4]>=35&&r[4]<=80);ok(r[5]===null||r[5]>=10&&r[5]<=100);ok(r[9]>=1);}
const tokyo=UNIVERSITIES.find(u=>u.name==='東京大学'),keio=UNIVERSITIES.find(u=>u.name==='慶應義塾大学'),waseda=UNIVERSITIES.find(u=>u.name==='早稲田大学');
eq(A.route(tokyo,tokyo.courses[5]).deviation,72.5);eq(A.route(tokyo,tokyo.courses[5]).commonBorder,90);
{const s=at(),c=keio.courses.find(c=>c.faculty==='経済学部'),routes=A.routes(keio,c);ok(A.subjectSet(s,keio,c,routes.find(r=>r.department.includes('A方式'))).individual.includes('mathII'));ok(!A.subjectSet(s,keio,c,routes.find(r=>r.department.includes('B方式'))).individual.includes('mathII'));}
{const c=waseda.courses.find(c=>c.department==='国際政治経済学科');ok(A.routes(waseda,c).every(r=>r.reference||r.department.includes('国際政治経済')),'Do not mislabel Politics/Economics as International Political Economy');}
// Probabilities have no lower floor, are monotone in preparation, and need the right math.
{const s=at();for(const k of Object.keys(s.subjects))s.subjects[k]=15;eq(A.estimate(s,tokyo,tokyo.courses[5],null,false).probability,0);let prev=0;for(let v=0;v<=200;v+=5){for(const k of Object.keys(s.subjects))s.subjects[k]=v;const p=A.estimate(s,tokyo,tokyo.courses[5],null,false).probability;ok(p>=prev&&p>=0&&p<1);prev=p;}ok(prev>.9);}
{const s=at(10);s.skills.math=200;s.subjects.mathI=200;s.subjects.mathII=200;s.learning.arithmetic=s.learning.juniorMath=200;s.subjects.mathIII=s.subjects.higherMath=0;const e=D.EXAMS.find(e=>e.id==='suken12');eq(E.examProbability(s,e,false),0);s.subjects.mathIII=200;eq(E.examProbability(s,e,false),0);s.subjects.higherMath=200;ok(E.examProbability(s,e,false)>.95);}
{const s=at(10);s.plan.mathTrack='mathIII';s.subjects.mathII=90;const before=s.subjects.mathIII;tick(s);ok(s.subjects.mathIII>before,'Age does not forbid advanced mathematics');}
// Presets store copies, survive save/reload, and carry forward into a new year.
{const s=at(15);s.plan.mathTrack='mathIII';eq(N.savePreset(s,'理系'), '');const saved=E.copy(s.presets[0]);s.plan.allocation.study=2;s.plan.allocation.rest=4;s.plan.mathTrack='mathI';eq(s.presets[0],saved);eq(N.loadPreset(s,0),'');eq(s.plan.allocation,saved.allocation);eq(s.plan.mathTrack,'mathIII');tick(s);eq(s.plan.allocation,saved.allocation);eq(s.plan.mathTrack,'mathIII');eq(s.presets[0],saved);}
// Family funds cannot be cashed out by a child, and purchases cannot be repeated for profit.
{const s=at(10);s.cash=0;s.parents.educationFund=10;s.plan.purchaseFunding='parent';const i=D.ITEMS.find(i=>i.id==='dictionary');eq(E.buy(s,i.id),'');near(s.parents.educationFund,10-i.price);eq(E.sell(s,i.id),'');eq(s.cash,0);ok(s.parents.educationFund<10);ok(!!E.buy(s,i.id));ok(!!E.buy(s,'console'));ok(!!E.action(s,'campus:home'));}
{const s=E.newGame({seed:'baby',pacing:'term'});for(let i=0;i<18;i++)tick(s);eq(s.age,6);eq(s.debt,0);eq(s.cash,0);ok(s.parents.educationFund<=100);}
// Term mode pays one salary, one school year, one fee, and one annual top-up.
{const a=at(30),b=E.copy(a);b.pacing='term';a.job=b.job='office';a.stats.stress=b.stats.stress=0;const annual=E.annualBudget(b).income;const cash=b.cash;tick(b);eq(b.age,30);eq(b.period,1);eq(b.pensionYears,0);tick(b);eq(b.age,30);tick(b);eq(b.age,31);eq(b.period,0);eq(b.pensionYears,1);near(b.report.income,annual);ok(b.cash-cash<annual);eq(b.termPlans.length,0);}
{const s=at(17,'term');s.school.hsProgress=2;s.plan.exams=['boki3'];s.skills.business=200;const fee=D.EXAMS.find(e=>e.id==='boki3').fee;const original=N.periodBudget(s,E.annualBudget(s));tick(s);eq(s.highschoolGrad,false);eq(s.certs.boki3,undefined);tick(s);eq(s.highschoolGrad,false);tick(s);ok(s.highschoolGrad);eq(s.examAttempts.boki3,1);ok(s.certs.boki3!==undefined);}
{const s=at(30,'term');s.plan.experience='abroad_short';const cost=D.EXPERIENCES.find(x=>x.id==='abroad_short').cost;let sum=0;for(let i=0;i<3;i++){const b=N.periodBudget(s,E.annualBudget(s));sum+=b.experienceCost;tick(s);}near(sum,cost);eq(s.experienceCounts.abroad_short,1);}
{const s=at(30,'term');s.plan.experience='reskill';tick(s);s.plan.experience=null;ok(!!E.advance(s).error);s.plan.experience='reskill';tick(s);tick(s);eq(s.experienceCounts.reskill,1);}
// Credit requirements, dropping out, and equivalency remain independent routes.
{const s=at(17);s.school.hsProgress=2;s.plan.attendance='rare';tick(s);eq(s.school.hsProgress,2);eq(s.highschoolGrad,false);eq(s.school.repeats,1);s.plan.attendance='regular';tick(s);eq(s.highschoolGrad,true);}
{const s=at(16);eq(E.action(s,'high-dropout'),'');nextYear(s);eq(s.highschoolGrad,false);s.certs.highschool=17;ok(!E.universityEligibility(s,tokyo,tokyo.courses[0]));}
// Shared planning capacity, minors' gates and optional spending are enforced in the engine.
{const s=at(17);s.plan.drinkDays=1;ok(!!E.advance(s).error);s.plan.drinkDays=0;s.plan.ai='verify';ok(!!E.advance(s).error);s.parents.trust=60;eq(E.action(s,'ai-permission'),'');s.plan.drivingPractice=1;ok(!!E.advance(s).error);}
{const s=at(18);s.cash=0;s.plan.travelFrequency=12;ok(!!E.advance(s).error);s.cash=3000;s.plan.codePractice=3;s.plan.musicPractice=3;ok(!!E.advance(s).error);}
// The licence takes actual preparation and is not the old one-click test.
{const s=at(17,'term');s.skills.tech=70;eq(E.action(s,'driving-enroll'),'');const cash=s.cash;ok(!!E.action(s,'driving-enroll'));eq(s.cash,cash);s.plan.drivingPractice=1;tick(s);eq(s.certs.driver,undefined);ok(s.driving.stage==='school');tick(s);eq(s.certs.driver,undefined);tick(s);eq(s.certs.driver,18);eq(s.driving.stage,'licensed');eq(s.plan.drivingPractice,0);eq(s.driving.tests,1);}
{const s=at(20,'term');s.skills.tech=70;eq(E.action(s,'driving-enroll'),'');s.plan.drivingPractice=1;s.driving.theory=26;s.driving.practice=31;tick(s);eq(s.age,20);eq(s.certs.driver,20);}
// Frequency changes pay for the actual whole trips in that period.
{const s=at(30,'term');s.period=1;s.plan.travelFrequency=0;const base=N.periodBudget(s,E.annualBudget(s));s.plan.travelFrequency=2;const trips=N.periodBudget(s,E.annualBudget(s));near(trips.expenses-base.expenses,22);}
// The rare aviation paths are exercised directly, without amplifying live probabilities.
{const s=at(30);s.lifeMode='natural';s.plan.travelFrequency=1;const report=[];N.perPeriod(s,report,()=>0,1);ok(s.finished);eq(s.endCause,'航空事故');}
{const s=at(30);s.lifeMode='natural';s.plan.travelFrequency=1;const report=[];N.perPeriod(s,report,()=>.5e-6,1);ok(!s.finished);ok(report.some(r=>r.kind==='fail'));}
// A common test attempt is capped; taking mocks never improves academic scores.
{const s=at(17);const old=E.copy(s.subjects);for(let i=0;i<3;i++)eq(A.mock(s),'');ok(!!A.mock(s));eq(s.subjects,old);eq(s.admissions.mocks.length,3);ok(s.admissions.mocks.every(m=>m.total>=0&&m.total<=1000));}
// Standard national front/late + private併願; low ability never gets a miracle floor.
{const s=at(),lateUni=UNIVERSITIES.find(u=>u.type==='国立'&&u.courses.some(c=>A.routes(u,c).some(r=>r.round==='後期')));const ci=lateUni.courses.findIndex(c=>A.routes(lateUni,c).some(r=>r.round==='後期')),lr=A.routes(lateUni,lateUni.courses[ci]).find(r=>r.round==='後期');eq(A.add(s,{university:tokyo.id,course:0,mode:'full'}),'');ok(!!A.add(s,{university:tokyo.id,course:1,mode:'full'}));eq(A.add(s,{university:lateUni.id,course:ci,mode:'full',route:lr.id}),'');eq(A.add(s,{university:keio.id,course:0,mode:'full'}),'');for(const k of Object.keys(s.subjects))s.subjects[k]=200;const report=[];A.settle(s,report,()=>0);eq(s.education.university,tokyo.id);ok(s.admissions.results.find(r=>r.round==='後期').skipped);ok(E.validateState(s));}
{const s=at(17,'term');s.school.hsProgress=2;s.plan.attendance='rare';tick(s);tick(s);s.plan.attendance='regular';tick(s);ok(!s.highschoolGrad,'Attendance in only the final third is insufficient');}
{const s=at(17);s.school.hsProgress=2;eq(A.add(s,{university:tokyo.id,course:0,mode:'full'}),'');s.plan.attendance='rare';for(const k of Object.keys(s.subjects))s.subjects[k]=200;tick(s);ok(!s.education,'No university admission without actual high-school completion or equivalency');}
// Quizzes have four distinct answers, deterministic generation and only one reward.
{const seen=new Set();for(let i=0;i<400;i++){const s=at(17,'year','quiz-'+i);s.plan.mathTrack='mathIII';const q=Q.get(s);eq(new Set(q.choices).size,4);ok(q.correct>=0&&q.correct<4);ok(q.tag==='数Ⅲ');seen.add(q.prompt);const before=s.subjects.mathIII;ok(Q.answer(s,q.correct).correct);near(s.subjects.mathIII,before+.8,.0001);ok(!!Q.answer(s,q.correct).error);eq(Q.get(E.copy(s)),q);}ok(seen.size>=250,'Generated coefficient variants vary');}
for(const subject of ['social','english','coding']){const s=at(17);s.plan.quizSubject=subject;const q=Q.get(s);ok(q.factIndex>=0);ok(Q.answer(s,q.correct).correct);ok(E.validateState(s));}
// Repetition saves input, with a visible learning cost and stops at decisions.
{const a=E.newGame({seed:'auto',lifeMode:'century'}),b=E.copy(a);const r=N.autoAdvance(a,10);eq(r.years,10);for(let i=0;i<10;i++)tick(b);ok(a.subjects.japanese<b.subjects.japanese);eq(a.autoYears,10);const stop=N.autoAdvance(a,10);eq(a.age,11);ok(stop.stop.includes('進路'));ok(E.validateState(a));}
// Rating/music progress is bounded, and invitation cannot be repeated without new points.
{const s=at(20,'term');s.plan.allocation={study:2,work:0,health:2,social:1,creative:5,rest:2};s.items.push({id:'laptop',bought:20},{id:'instrument',bought:20});s.plan.codePractice=3;s.plan.musicPractice=2;s.plan.competitionFrequency=12;s.skills.tech=160;s.subjects.mathII=150;s.competition.algorithm=160;nextYear(s);eq(s.competition.entries,12);ok(s.competition.rating>0&&s.competition.rating<=4000);ok(s.music.skill>0);}
// Invalid frequency, partial-period and preset data must not be accepted on import.
{const s=at();for(const mutate of [b=>b.plan.travelFrequency=-1,b=>b.plan.drinkDays=Infinity,b=>b.period=2,b=>b.presets=[{name:'bad',allocation:{study:999},subjectWeights:Array(14).fill(0)}],b=>b.driving.practice=-1,b=>b.competition.entries=-1,b=>b.music.awards=-1,b=>b.plan.sciencePair='cash,health']){const bad=E.copy(s);mutate(bad);ok(!E.validateState(bad));}}
// Paired full-lifespan runs cover both modes and four starting environments.
const lives=[];for(const pacing of ['year','term'])for(const origin of ['easy','medium','hard','draw'])for(let seed=0;seed<3;seed++){const s=E.newGame({origin,pacing,seed:`v4-life-${seed}`,lifeMode:'natural'});while(!s.finished){if(s.age>=18){s.plan.allocation={study:2,work:2,health:3,social:2,creative:1,rest:2};const j=D.JOBS.find(j=>j.id==='office');if(!s.job&&!E.jobEligibility(s,j))s.plan.job=j.id;}if(s.age>=70)s.plan.allocation={study:1,work:0,health:4,social:2,creative:1,rest:4};tick(s);ok(s.age<=100);ok(E.score(s).total>=0&&E.score(s).total<=100);}lives.push({origin,pacing,age:s.age,wealth:E.netWorth(s),score:E.lifeSummary(s).total});}
const result={passed:true,checks,periods,lifeRuns:lives.length,coverage:A.coverage,lives};fs.mkdirSync(qa,{recursive:true});fs.writeFileSync(path.join(qa,'v4-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,lives:undefined}));
