const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=fs.existsSync(path.join(__dirname,'index.html'))?__dirname:path.join(__dirname,'..'),assets=fs.existsSync(path.join(root,'dist/index.html'))?path.join(root,'dist'):root;
const qa=fs.existsSync(path.join(root,'tools'))?path.join(root,'qa'):root;
global.window=global;for(const n of ['universities','data','world','systems','chapters','admission-data','admission-rules','admissions','quiz','next','engine'])require(path.join(assets,n+'.js'));
const D=LifeData,E=LifeEngine,X=LifeSystems;let checks=0,years=0;const ok=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++};
function tick(s){s.plan.event??=0;const r=E.advance(s);ok(!r.error,r.error);ok(E.validateState(s),'Save valid after age '+s.age);years++;return r;}
function at(age,extra={}){const s=E.newGame({seed:'systems',lifeMode:'century',...extra});s.age=age;s.cash=10000;s.highschoolGrad=age>=18;s.school.hsProgress=age>=18?3:Math.max(0,age-15);Object.keys(s.skills).forEach(k=>s.skills[k]=120);Object.keys(s.subjects).forEach(k=>s.subjects[k]=120);s.stats.discipline=70;s.learning.arithmetic=s.learning.juniorMath=120;s.plan.allocation={study:4,work:1,health:2,social:2,creative:1,rest:2};return s;}
// Initial conditions affect resources without assigning moral value by birthplace or income.
{const easy=E.newGame({origin:'easy',seed:'o'}),hard=E.newGame({origin:'hard',seed:'o'});ok(easy.parents.educationFund>hard.parents.educationFund);eq(easy.inner.integrity,hard.inner.integrity);eq(D.PREFECTURES.length,47);eq(new Set(D.PREFECTURES.map(x=>x.id)).size,47);eq(E.newGame({origin:'draw',prefecture:'random',seed:'repeat'}),E.newGame({origin:'draw',prefecture:'random',seed:'repeat'}));const s=at(18);s.home=null;const born=s.birthPref;eq(E.action(s,'move:13'),'');eq(s.birthPref,born);eq(s.prefecture,'13');}
// School departure, second chances, no automatic graduation, and unlimited preparation.
{const s=at(8);ok(!!E.action(s,'campus:home'));ok(E.educationName(s).includes('小学校'));s.age=12;eq(E.action(s,'campus:support'),'');tick(s);ok(E.validateState(s));}
{const s=at(17);s.highschoolGrad=false;s.school.hsProgress=2;eq(E.action(s,'high-dropout'),'');tick(s);ok(!s.highschoolGrad,'Leaving school must not graduate automatically at 18');s.plan.school='high_remote';tick(s);eq(s.highschool,'remote');eq(s.school.hsProgress,2,'Prior completed years retained');tick(s);ok(s.highschoolGrad,'Correspondence return can complete school');s.age=52;eq(E.action(s,'ronin'),'');s.school.roninYears=30;tick(s);eq(s.school.roninYears,31,'No arbitrary repeat-year cap');}
{const s=at(14);s.highschoolGrad=false;s.plan.school='kosen';eq(X.schoolProbability(s,'kosen'),1);tick(s);eq(s.age,15);eq(s.education.kind,'kosen');eq(s.education.progress,0,'New entry must not earn a year immediately');for(let i=0;i<5;i++)tick(s);ok(s.degrees.some(d=>d.kind==='kosen'));eq(s.age,20);eq(E.action(s,'kosen-transfer'),'');eq(s.education.total,2);for(let i=0;i<2;i++)tick(s);ok(E.hasDegree(s,'tech'));}
{const s=at(15);s.plan.subjectWeights[0]--;ok(!!E.advance(s).error);ok(E.validateState(s),'Partial time allocation should still be savable');s.plan.subjectWeights[0]++;s.plan.curriculum='cpa';s.plan.focus='business';ok(!E.examEligibility(s,D.EXAMS.find(e=>e.id==='cpa_short')));s.skills.business=200;s.skills.law=180;s.stats.stress=0;eq(E.examProbability(s,D.EXAMS.find(e=>e.id==='cpa_short')),1,'Sufficient preparation removes exam randomness');s.plan.exams=['cpa_short','cpa'];tick(s);ok(s.certs.cpa!==undefined,'Prepared high-school student may pass both stages');ok(!s.licenses.includes('cpa'),'Passing does not bypass professional registration');}
{const s=at(18,{prefecture:'13'}),u=UNIVERSITIES.find(u=>u.name==='信州大学'),course=u.courses.findIndex(c=>c.field==='science');Object.keys(s.subjects).forEach(k=>s.subjects[k]=190);LifeAdmissions.add(s,{university:u.id,course,mode:'full'});tick(s);eq(s.prefecture,'20','Official short prefecture names map to full region names on admission');}
// Subject preparation and interviews make distinct contributions.
{const u=UNIVERSITIES.find(u=>u.name==='東京科学大学'),c=u.courses.find(c=>c.field==='tech'),a=at(17),b=E.copy(a);for(const k of ['mathII','physics','chemistry'])a.subjects[k]=10;ok(E.admissionProbability(b,u,c)>E.admissionProbability(a,u,c));const j=D.JOBS.find(j=>j.id==='engineer');a.skills.tech=b.skills.tech=60;a.inner.interview=0;b.inner.interview=90;ok(E.jobProbability(b,j)>E.jobProbability(a,j));const old=E.jobProbability(b,j);b.inner.integrity=1;eq(E.jobProbability(b,j),old,'Interview presentation is not omniscient character detection');}
// Account learning gates, help, real costs and locked business capital.
{const s=at(20);s.inner.financial=s.inner.digital=0;s.account.credit=0;ok(!!E.action(s,'account'));ok(!s.account.open);eq(s.account.attempts,1);eq(E.action(s,'account-assisted'),'');ok(s.account.open,'Low credit alone does not bar an ordinary cash account');const w=E.netWorth(s);eq(E.invest(s,100),'');eq(E.netWorth(s),w);}
{const s=at(30);s.skills.business=s.skills.law=150;s.inner.financial=s.inner.digital=90;s.inner.integrity=10;s.inner.workReputation=80;s.stats.trust=80;eq(E.action(s,'venture:brokerage'),'');s.venture.years=2;ok(E.action(s,'broker-register').includes('誠実さ'));s.inner.integrity=90;const w=E.netWorth(s);eq(E.action(s,'broker-register'),'');eq(s.venture.capital,5000);eq(E.netWorth(s),w-100,'Registration cost, not capital transfer, reduces net worth');ok(s.cash<5000,'Capital cannot also be spent as personal cash');ok(!!E.invest(s,5000));eq(E.action(s,'broker-close'),'');eq(s.venture.capital,0);ok(!!E.action(s,'broker-close'),'No repeated capital release');}
// Suspended capital remains recoverable and cannot survive asset liquidation.
{const s=at(30);s.venture={kind:'brokerage',years:3,registered:false,capital:5000};const w=E.netWorth(s);ok(!!E.action(s,'broker-register'));ok(!!E.action(s,'venture:product'));eq(E.netWorth(s),w);eq(E.action(s,'broker-close'),'');eq(E.netWorth(s),w-500);}
{const s=at(30);s.venture={kind:'brokerage',years:3,registered:true,capital:5000};s.debt=600;eq(E.action(s,'rebuild'),'');eq(s.venture.capital,0);ok(!s.venture.registered);ok(!!E.action(s,'broker-close'));eq(E.netWorth(s),15-180);}
// All controlled habits gate at 20; annual stakes are bounded and repeatable.
{const s=at(19);s.plan.gambling='high';ok(!!E.advance(s).error);ok(!E.validateState(s));s.age=20;ok(E.validateState(s));s.plan.drinkDays=180;s.plan.cigarettes=10;tick(s);ok(s.body.alcoholDependence>0&&s.body.tobaccoDependence>0&&s.body.gamblingDependence>0);const dep=s.body.tobaccoDependence;s.plan.cigarettes=0;tick(s);ok(s.body.tobaccoDependence<dep);}
// Overseas years cannot earn the same school year or salary twice.
{const s=at(20);s.education={kind:'college',name:'工学課程',field:'tech',total:4,progress:1,tuition:54,mode:'full',paused:false};s.plan.experience='exchange';tick(s);eq(s.education.progress,1);eq(s.visits,1);ok(s.experienceCounts.exchange===1);s.plan.experience=null;tick(s);eq(s.education.progress,2);}
{const s=at(26);s.job='engineer';s.plan.experience='overseas_work';eq(E.salary(s),0);const before=s.skills.english;tick(s);ok(s.skills.english>before);eq(s.experience.freelance,1);}
// Work styles are job-specific; fatigue and reputation are not UI-only counters.
{const a=at(30),b=E.copy(a);a.job=b.job='engineer';a.plan.workstyle='remote';b.plan.workstyle='office';tick(a);tick(b);ok(a.inner.fatigue<=b.inner.fatigue);ok(a.stats.connections<b.stats.connections);}
{const a=at(32),b=E.copy(a);a.job=b.job='office';a.jobYears=b.jobYears=3;a.inner.integrity=10;b.inner.integrity=90;tick(a);tick(b);ok(a.inner.workReputation<b.inner.workReputation);ok(a.stats.trust<b.stats.trust);}
// Story arcs persist the selected branch and connect later consequences.
{const s=at(24);s.job='influencer';s.eventId='arc_influencer_1';s.plan.event=1;tick(s);eq(s.arcs.influencer.stage,2);ok(s.storyFlags.hype!==undefined);s.eventId='arc_influencer_2';s.plan.event=0;const r=tick(s);ok(r.report.entries.some(e=>e.text.includes('以前、検証せず')));}
// Disease provides an interval to act; natural ageing and century mode differ.
{const a=at(70,{lifeMode:'natural'}),b=E.copy(a);a.body.condition=b.body.condition='治療中の病気';a.body.severity=b.body.severity=50;a.plan.care='treatment';b.plan.care='routine';tick(a);tick(b);ok(a.body.severity<b.body.severity);ok(!a.finished&&!b.finished);}
{const s=at(60,{lifeMode:'natural'});s.body.condition='重い病気';s.body.severity=100;s.body.burden=100;s.body.critical=0;s.stats.health=5;s.stats.stress=100;s.plan.allocation={study:6,work:6,health:0,social:0,creative:0,rest:0};tick(s);ok(!s.finished,'One bad year cannot trigger immediate disease death');tick(s);ok(!s.finished,'Warning period continues');tick(s);ok(s.finished&&s.endCause==='病気');}
{const a=at(95,{lifeMode:'natural'}),b=at(95,{lifeMode:'century'});a.body.frailty=b.body.frailty=90;tick(a);tick(b);ok(a.finished&&a.endCause==='老衰');ok(!b.finished);}
// Prior saves migrate once, remain serializable, and preserve the old fixed-lifespan mode.
{const s=at(25),old=E.copy(s);for(const k of ['nextVersion','pacing','period','termPlans','termReports','presets','autoYears','parents','learning','admissions','driving','competition','music','quiz','yearStats','yearExperiencePaid','workCulture','expansion','origin','family','birthPref','prefecture','inner','subjects','school','body','arcs','storyFlags','account','venture','experienceCounts','admissionAttempts','yearMemo','endCause','lastPattern','patternYears','visits','lifeMode'])delete old[k];const migrated=E.migrate(old);ok(E.validateState(migrated));eq(migrated.lifeMode,'century');eq(E.migrate(E.copy(migrated)),migrated);const bad=E.copy(migrated);bad.venture={kind:'brokerage',registered:true,years:2,capital:Infinity};ok(!E.validateState(bad));}
// A varied long-run sample exercises origins, later careers, habits, illness and save round-trips.
const results=[];
for(const policy of ['careful','adventurous','burnout','research','media','nightlife'])for(let seed=0;seed<4;seed++){
 const s=E.newGame({seed:'expanded-'+policy+seed,origin:['easy','medium','hard','draw'][seed],prefecture:'random',lifeMode:'natural'});
 while(!s.finished){s.plan.event=seed%3;s.plan.allocation=policy==='burnout'?{study:4,work:4,health:0,social:1,creative:1,rest:2}:{study:4,work:1,health:2,social:2,creative:1,rest:2};if(s.age>=65&&policy!=='burnout')s.plan.allocation={study:1,work:0,health:4,social:2,creative:2,rest:3};
  s.plan.focus=policy==='research'?'science':policy==='media'?'arts':policy==='nightlife'?'language':s.age%4===0?'tech':'business';
  if(s.age>=20){s.plan.drinkDays=['nightlife','burnout'].includes(policy)&&s.cash>200?180:0;s.plan.cigarettes=policy==='burnout'&&s.cash>200?10:0;s.plan.gambling=policy==='adventurous'?'small':'none';s.plan.care=policy==='careful'?'prevent':s.body.condition&&policy!=='burnout'?'treatment':'routine';}
  if(s.age>=18){const desired=policy==='media'?'influencer':policy==='nightlife'?'host':policy==='research'?'lab_support':'office',j=D.JOBS.find(j=>j.id===desired);if(s.job!==desired&&!E.jobEligibility(s,j))s.plan.job=desired;if(s.cash>800&&!s.account.open)E.action(s,'account-assisted');if(s.account.open&&s.cash>800)E.invest(s,50);}
  if(s.age>=12&&policy==='research'&&s.skills.science>40)s.plan.project='research';
  if(policy==='adventurous'&&s.age%5===0&&!X.experienceEligible(s,'abroad_short'))s.plan.experience='abroad_short';
  if(s.age>=8&&s.age%9===0&&!X.experienceEligible(s,'local'))s.plan.experience='local';
  tick(s);ok(s.age<=100);ok(Number.isFinite(E.netWorth(s)));}
 results.push({policy,seed,age:s.age,end:s.endCause||'100歳の区切り',wealth:E.netWorth(s),health:s.stats.health,visited:s.visits,arcs:Object.keys(s.arcs)});
}
fs.mkdirSync(qa,{recursive:true});fs.writeFileSync(path.join(qa,'expanded-results.json'),JSON.stringify({checks,years,lifeRuns:results.length,results},null,2));
console.log(JSON.stringify({passed:true,checks,years,lifeRuns:results.length,endings:results.map(x=>({policy:x.policy,age:x.age,end:x.end}))},null,2));
